### ISSUE TITLE
0/1 Knapsack problem

### ISSUE THREAD

**Issue by Petersteve** [KaiyangZhou/pytorch-vsumm-reinforce#1]
Hi @KaiyangZhou 
What is the relation between  0/1 Knapsack problem and the summary video ?
I saw the 0/1 Knapsack problem  was used in the evaluate step in the implementation, Why? I want a detailed explanation for this last.
and thank you in advance.

**Comment by KaiyangZhou** [comment]
The knapsack algorithm is used to select a subset of shots with the maximum scores while ensuring the length does not exceed a threshold. An alternative way is the greedy selection, but it turned out to be inferior.

**Comment by Petersteve** [comment]
In this case we need for each frame his score ,isn't in unsupervised learning we don't need gtscore?

**Comment by KaiyangZhou** [comment]
knapsack is used in inference so the scores are predicted by the network

**Comment by Petersteve** [comment]
![image](https://user-images.githubusercontent.com/37736015/41125674-0fa7553e-6a9d-11e8-8400-aabd027e9b88.png)

**Comment by Petersteve** [comment]
![image](https://user-images.githubusercontent.com/37736015/41125699-1fa39d8a-6a9d-11e8-8d08-5837028e2323.png)
P t-1 ,  P , P t+1... is this the scores predicted by the network?

**Comment by KaiyangZhou** [comment]
yes, after the score prediction, we average scores within the same shot to get shot level scores, then select a subset of them to construct a summary
