### ISSUE TITLE
How can I get to know where frames are saved?

### ISSUE THREAD

**Issue by Swati640** [KaiyangZhou/pytorch-vsumm-reinforce#17]
While video summarization from given datasets, I can not see any folder where frames are saved and its throwing an error 
error: C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp:3289: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

 The network is not able to pick the frames as there is no existing folder and its throwing this error. Can you please help

**Comment by SinDongHwan** [comment]
you should download dataset. and then convert to frames from videos. 

reference this #15.
