### ISSUE TITLE
Bernoulli distribution

### ISSUE THREAD

**Issue by Petersteve** [KaiyangZhou/pytorch-vsumm-reinforce#3]
Hi @KaiyangZhou,
![image](https://user-images.githubusercontent.com/37736015/41507439-567902b6-722a-11e8-88a1-0d85e423d455.png)
![image](https://user-images.githubusercontent.com/37736015/41507507-643d683c-722b-11e8-964e-599592841099.png)
1/ What's the value of m? (m = Bernoulli(probs))
2/  what's the values of the probability Pt in case of  , At (action) equal =1?

**Comment by KaiyangZhou** [comment]
m is not a scalar but a torch distribution class which can generate binary values (for bernoulli distribution) based on given probs.

P_t is produced by the network which is trained to give high probs to good frames and give low probs to useless frames.

**Comment by KaiyangZhou** [comment]
The probability is just an indicator. The action is sampled from [Bernoulli distribution](https://en.wikipedia.org/wiki/Bernoulli_distribution).

Episodic RL is to reduce variance. Please refer to the [RL book by Sutton](http://incompleteideas.net/book/bookdraft2017nov5.pdf) for the background knowledge

**Comment by Petersteve** [comment]
![image](https://user-images.githubusercontent.com/37736015/41529273-70a0e996-72e4-11e8-8cc5-51c9360e86f6.png)
* They take the value 1 with probability p .... what's the mim value of this p?
