### ISSUE TITLE
Not able to  create H5 file for another video dataset

### ISSUE THREAD

**Issue by Swati640** [KaiyangZhou/pytorch-vsumm-reinforce#31]
I tried to use "https://github.com/SinDongHwan/pytorch-vsumm-reinforce/blob/master/utils/generate_dataset.py" , to extract features from another dataset using python 2.7(As recommended). But, cv2 function like cv2.cv.CV_CAP_PROP_FPS is not working and extracting the frames. And when  I tried to use it in python 3.6. I could extract the frames, but weave library is not supported and could not find its replica in 3.6(which we need to find change points). Please suggest, if someone has worked on their own dataset to create H5 file.

**Comment by SinDongHwan** [comment]
Hi,
Couldn't you use cv2.CAP_PROP_FPS?


2019년 9월 8일 (일) 오전 5:00, Swati640 <notifications@github.com>님이 작성:

**Comment by Swati640** [comment]
i was using old version of cv2(2,4),later i upgraded to cv2(4.1) and used CV2.CAP_PROP_FPS and it worked, with little changes in the code. :)
