### ISSUE TITLE
how to extracted key_frame from dataset?

### ISSUE THREAD

**Issue by harvestlamb** [KaiyangZhou/pytorch-vsumm-reinforce#37]
how to extracted key_frame from dataset?
when i try to run the step of **Visualize summary** ,i encounter with a problem.  I can't extracted key_frame from dataset,so i want konw how do this step?
@KaiyangZhou @yrwangxd @SinDongHwan

**Comment by SinDongHwan** [comment]
@harvestlamb 
Hi, Did you extract from model?

**Comment by harvestlamb** [comment]
> @harvestlamb
> Hi, Did you extract from model?

Nice to meet you,i think tht i should extracted video frames from summe dataset( 25 videos),what'more , i will  refer to your code of  answer  in  #35 ,if i have questions, i will try to contact you about this question. thank you very much.

**Comment by yrwangxd** [comment]
@harvestlamb hi, if you use the model to generate summery video. the generated file result.h5 have the machine_summary key,the value of the key represent the summary video . for example,if the video have 10 frames,the value of the key will be such as 0100010010.the summary video will contain the 2 6 9 frame and will have 3 frames.

**Comment by harvestlamb** [comment]
https://www.bugcodemaster.com/article/extract-images-frame-frame-video-file-using-ffmpeg

**Comment by SinDongHwan** [comment]
@harvestlamb 

The link don't extract key-frame from video.
Just convert video to frames.

**Comment by harvestlamb** [comment]
@SinDongHwan when i run this command:"ffmpeg -i Cooking.webm -vf "select=eq(pict_type\,I)" -vsync vfr %06d.jpg -hide_banner",it can be produce key frame,if i refer another answer,should i analyze the file of result.h5 to produce keyframe?

**Comment by SinDongHwan** [comment]
@harvestlamb 
I think you ran the command to extract key-frame using ffmpeg.
result.h5 is a summarized result from original video, and composed values {0,1}. 
if value is 0, not key-frame. if value is 1, key-frame.
if you can run "summary2video.py", you can get a summarized video from result.h5 file.
before run "summary2video.py", you have to prepare frames of each videos.

**Comment by sky-16** [comment]
> @harvestlamb
> I think you ran the command to extract key-frame using ffmpeg.
> result.h5 is a summarized result from original video, and composed values {0,1}.
> if value is 0, not key-frame. if value is 1, key-frame.
> if you can run "summary2video.py", you can get a summarized video from result.h5 file.
> before run "summary2video.py", you have to prepare frames of each videos.

How to prepare frames of each video before running "summary2video.py"
