### ISSUE TITLE
Handling one or zero frame selected bug

### ISSUE THREAD

**Issue by adamsvystun** [KaiyangZhou/pytorch-vsumm-reinforce#4]
When Bernoulli sampling returns zero or one frame, training crashes.

First, if Bernoulli sampling selects one frame, this error will occur `TypeError: len() of a 0-d tensor`. This happens because the line 17 in rewards.py `pick_idxs = _actions.squeeze().nonzero().squeeze()` will return tensor of dimension 0, and when later on line 18 `num_picks = len(pick_idxs)` function len is called - error will be thrown.

Example to reproduce the error:
```
import torch
from torch.distributions import Bernoulli

m = Bernoulli(torch.tensor([0.0, 0.0, 1.0, 0.0, 0.0]))
actions = m.sample()

pick_idxs = _actions.squeeze().nonzero().squeeze()
print(len(pick_idxs))
```

Second, when zero or one frame is selected, return of `compute_reward` function should be tensor of size 0, otherwise line 132 in main.py will produce size mismatch error. So lines 22 `reward = torch.tensor([0.])` and 31 `reward = torch.tensor([0.])` should be replaced with `reward = torch.tensor(0.)`.

Can somebody confirm these bugs? (So I can maybe commit the fix?)

pytorch version: 0.4.0
python version: 2.7.12

**Comment by KaiyangZhou** [comment]
You are right. Thanks for spotting this.

To overcome the 1st issue, you can do
```
num_picks = len(pick_idxs) if pick_idxs.ndimension() > 0 else 1
```

The 2nd issue can be resolved by your solution.

I will update the code.
