### ISSUE TITLE
the link of dataset can't found

### ISSUE THREAD

**Issue by xiongma** [KaiyangZhou/pytorch-vsumm-reinforce#59]
when I used your recommendation to download dataset , 
```
wget http://www.eecs.qmul.ac.uk/~kz303/vsumm-reinforce/datasets.tar.gz
```
it returned 404

**Comment by SinDongHwan** [comment]
hi, @xiongma 

Hi, you can download dataset on [this link.](https://drive.google.com/file/d/1XFizLbkpMX0NoPAe1P1WtvVn9KLwbZ7C/view)
Good Luck!!
