### ISSUE TITLE
error in summary2video.py

### ISSUE THREAD

**Issue by Sujit1011** [KaiyangZhou/pytorch-vsumm-reinforce#62]
Hello, I'm getting an error in this way

```
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x00000020/' ???'
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp, line 3289
Traceback (most recent call last):
  File "summary2video.py", line 42, in <module>
    frm2video(args.frm_dir, summary, vid_writer)
  File "summary2video.py", line 27, in frm2video
    frm = cv2.resize(frm, (args.width, args.height))
cv2.error: C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp:3289: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize
```

Can anyone resolve it for me, please

Thank you

**Comment by SinDongHwan** [comment]
Hi, @Sujit1011.
Check a "frm" variable.
Maybe image is not read.

**Comment by sky-16** [comment]
> Hi, @Sujit1011.
> Check a "frm" variable.
> Maybe image is not read.

From which folder I need to read image. I am unable to get your point.

**Comment by SinDongHwan** [comment]
Hi, @sky-16.
following a error is occured, when a image wasn't read. (i.e. "frm" variable is None.)
if not have a original dataset, you have to download it. and then convert videos to fraems.

> Hello, I'm getting an error in this way
> 
> ```
> OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
> OpenCV: FFMPEG: fallback to use tag 0x00000020/' ???'
> OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp, line 3289
> Traceback (most recent call last):
>   File "summary2video.py", line 42, in <module>
>     frm2video(args.frm_dir, summary, vid_writer)
>   File "summary2video.py", line 27, in frm2video
>     frm = cv2.resize(frm, (args.width, args.height))
> cv2.error: C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp:3289: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize
> ```
> 
> Can anyone resolve it for me, please
> 
> Thank you

**Comment by sky-16** [comment]
> Hi, @sky-16.
> following a error is occured, when a image wasn't read. (i.e. "frm" variable is None.)
> if not have a original dataset, you have to download it. and then convert videos to fraems.
> 
> > Hello, I'm getting an error in this way
> > ```
> > OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
> > OpenCV: FFMPEG: fallback to use tag 0x00000020/' ???'
> > OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp, line 3289
> > Traceback (most recent call last):
> >   File "summary2video.py", line 42, in <module>
> >     frm2video(args.frm_dir, summary, vid_writer)
> >   File "summary2video.py", line 27, in frm2video
> >     frm = cv2.resize(frm, (args.width, args.height))
> > cv2.error: C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp:3289: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize
> > ```
> > 
> > 
> > Can anyone resolve it for me, please
> > Thank you

I have downloaded the dataset mentioned in https://github.com/KaiyangZhou/pytorch-vsumm-reinforce/issues/40.
Is there any other dataset because in this one I can not find images that need to be read.
