### ISSUE TITLE
Confused in the command

### ISSUE THREAD

**Issue by Sujit1011** [KaiyangZhou/pytorch-vsumm-reinforce#64]
What will be in 'path_to' and 'video_frames' in the command

```bash
python summary2video.py -p path_to/result.h5 -d path_to/video_frames -i 0 --fps 30 --save-dir log --save-name summary.mp4
```

Can anyone resolve it for me, please

Thank you

**Comment by SinDongHwan** [comment]
Hi, @Sujit1011.

* path_to/result.h5 case
    - If you had run test step, result.h5 is created. 
      so, "path_to" is a directory path of result.h5 file
* path_to/video_frames
    - If you had downloaded original datasets and converted videos to frames, directories of frames are is created.
      so "path_to" is a directory path of frames.
    - "video_frames" is a directory path.

you can see a [description](https://github.com/KaiyangZhou/pytorch-vsumm-reinforce/blob/77f7c93249240d6fa297818c1eefd5c2b51b1747/summary2video.py#L9) about "-p" and "-d".

**Comment by Sujit1011** [comment]
> Hi, @Sujit1011.
> 
> * path_to/result.h5 case
>   
>   * If you had run test step, result.h5 is created.
>     so, "path_to" is a directory path of result.h5 file
> * path_to/video_frames
>   
>   * If you had downloaded original datasets and converted videos to frames, directories of frames are is created.
>     so "path_to" is a directory path of frames.
>   * "video_frames" is a directory path.
> 
> you can see a [description](https://github.com/KaiyangZhou/pytorch-vsumm-reinforce/blob/77f7c93249240d6fa297818c1eefd5c2b51b1747/summary2video.py#L9) about "-p" and "-d".

**Comment by Sujit1011** [comment]
Can you give some example
