### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'format'

### ISSUE THREAD

**Issue by anbuharry** [KaiyangZhou/pytorch-vsumm-reinforce#68]
after running this code i got these error 

python parse_log.py -p path_to/log_train.txt

Done video {}. # frames {}.
Traceback (most recent call last):
  File "visualize_results.py", line 36, in <module>
    print("Done video {}. # frames {}.").format( key, len(machine_summary))
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by SinDongHwan** [comment]
hi, @anbuharry/
you have a syntax error.
edit to a following code.
`print("Done video {}. # frames {}.".format(key, len(machine_summary)))`

good luck!

**Comment by anbuharry** [comment]
> hi, @anbuharry/
> you have a syntax error.
> edit to a following code.
> `print("Done video {}. # frames {}.".format(key, len(machine_summary)))`
> 
> good luck!

I had one more Doubt. I have features, gtscore all the thing to create a dataset 

Thank you
