### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by anbuharry** [KaiyangZhou/pytorch-vsumm-reinforce#71]
@SinDongHwan

Hai 
 I am getting this error while running Generate_dataset.py  Even after installing WEAVE 

Thanks 

```
(harry) vinsent@vinsent-H110M-H:~/Documents/sindong _vsumm/utils/KTS$ /bin/python3 "/home/vinsent/Documents/sindong _vsumm/utils/KTS/cpd_nonlin.py"

Traceback (most recent call last):
  File "/home/vinsent/Documents/sindong _vsumm/utils/KTS/cpd_nonlin.py", line 2, in <module>
    import weave
ModuleNotFoundError: No module named 'weave'

```

**Comment by SinDongHwan** [comment]
Hi, @anbuharry.
you have to run python 2.x.
python version over 3 doesn't support weave.

**Comment by anbuharry** [comment]
> Hi, @anbuharry.
> you have to run python 2.x.
> python version over 3 doesn't support weave.

Thanks  @SinDongHwan 

Is there any way to run this code without GPU?

**Comment by anbuharry** [comment]
> Hi, @anbuharry.
> you have to run python 2.x.
> python version over 3 doesn't support weave.

@SinDongHwan @KaiyangZhou 

```
Traceback (most recent call last):
  File "create_data.py", line 13, in <module>
    gen.generate_dataset()
  File "/content/Video-Summarization-Pytorch/generate_dataset.py", line 120, in generate_dataset
    change_points, n_frame_per_seg = self._get_change_points(video_feat, n_frames,fps)
  File "/content/Video-Summarization-Pytorch/generate_dataset.py", line 53, in _get_change_points
    n = n_frame / fps
ZeroDivisionError: float division by zero

```

**Comment by SinDongHwan** [comment]
hi, @anbuharry.
check a value of "fps" variable.
when 1/0 or 1.6/0, the error is occurred.

**Comment by anbuharry** [comment]
> hi, @anbuharry.
> check a value of "fps" variable.
> when 1/0 or 1.6/0, the error is occurred.

Thank you so much @SinDongHwan 

please help me out with this error

Traceback (most recent call last):
  File "summary2video.py", line 43, in <module>
    frm2video(args.frm_dir, summary, vid_writer)
  File "summary2video.py", line 27, in frm2video
    frm = cv2.resize(frm, (args.width, args.height))
cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by SinDongHwan** [comment]
hi, @anbuharry.
Check a value of "frm" variable.
when didn't read a image, following a error message is occurred.
`cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`

**Comment by anbuharry** [comment]
> hi, @anbuharry.
> Check a value of "frm" variable.
> when didn't read a image, following a error message is occurred.
> `cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`

Thanks a lot @SinDongHwan 

Finally, I got a video summary for my own data's thanks for your guidance. is there any way to run this code in the python3 version if yes what are the changes I need to do?

**Comment by anbuharry** [comment]
Hi @SinDongHwan @KaiyangZhou 

This time Queries from Rewards function 

How action had zero's and ones in Reward?

How Action derived?

How is action selecting frames?  is there any comparison that happened?

**Comment by TheMaveric** [comment]
> hi, @anbuharry.
> Check a value of "frm" variable.
> when didn't read a image, following a error message is occurred.
> `cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`

The path provided to the imread function is correct for me but for some reason it stops at frame #5795 for Eiffel Tower and gives this error.

**Comment by SinDongHwan** [comment]
hi, @TheMaveric.

Please check, video_num. 
ex)'video_1', 'video_2', 'video_3'
number of frames for a 'Eiffel Tower' video is  4971.
i think video index is mis-matched.

**Comment by anbuharry** [comment]
Hai @SinDongHwan  

I had one doubt in the final video generation.  I think this question is apart from this code if you know please help me.

If I want to reduce the final summary video by selecting only one frame per change point. how can do that

Thank you

**Comment by anbuharry** [comment]
Hello @SinDongHwan 

This error occurs in the summary2video.py file
```
cv2.VideoWriter_fourcc(*'mp4v')
TypeError: VideoWriter() missing required argument 'fourcc' (pos 3)
```
Could you please clarify why this error happens and how can I resolve this?

Thank you so much

**Comment by SinDongHwan** [comment]
Hi, @anbuharry.
Are your codes same this repository??

**Comment by anbuharry** [comment]
> Hi, @anbuharry.
> Are your codes same this repository??

Hi @SinDongHwan 

No, I try to get summary video in different way 

`[https://github.com/anbuharry/Torrient_fraction](url)`

**Comment by SinDongHwan** [comment]
Hi, @anbuharry 
Could i connect your pc on Teamviewer?

**Comment by anbuharry** [comment]
> Hi, @anbuharry
> Could I connect your pc on Teamviewer?

Hi @SinDongHwan 

yeah sure .. Will we do it tomorrow?

**Comment by SinDongHwan** [comment]
Hi, @anbuharry
I'm now okay. And you?
When can you do?

**Comment by anbuharry** [comment]
> Hi, @anbuharry
> I'm now okay. And you?
> When can you do it?
> if you can, send me the password.
> my email : [god.donghwan@gmail.com](mailto:god.donghwan@gmail.com)

Hi, @SinDongHwan 
 
ID and Password sent done to the email ID you provided

**Comment by anbuharry** [comment]
Hi @SinDongHwan 

How can I Extend frame runtime or how to fix frame run time in generated video?

Thank you
