### ISSUE TITLE
Question about Reward funtion ?

### ISSUE THREAD

**Issue by Chuttyboy** [KaiyangZhou/pytorch-vsumm-reinforce#73]
Hello @KaiyangZhou @SinDongHwan 

Could you please explain Equation 3 and 4  in Pytorch implemetation paper ?

![Kaiyang](https://user-images.githubusercontent.com/79959547/118431364-d0200680-b6f3-11eb-8f6b-0c295b0ce9fb.png)

Thank you

**Comment by anbuharry** [comment]
> Hello @KaiyangZhou @SinDongHwan
> 
> Could you please explain Equation 3 and 4 in Pytorch implemetation paper ?
> 
> ![Kaiyang](https://user-images.githubusercontent.com/79959547/118431364-d0200680-b6f3-11eb-8f6b-0c295b0ce9fb.png)
> 
> Thank you

Hi @Chuttyboy 

Rdiv = 1/(num_pick)(numpick-1)  ------- 3

d(x t , x t ') = 1. - torch.matmul(normed_seq, normed_seq.t()) is nothing but dissim_mat

below part  :   dissim_mat[pick_idxs,:][:,pick_idxs]

1 - dissim_mat / dissim_submat 

that all
