### ISSUE TITLE
Dataset for video summaization 

### ISSUE THREAD

**Issue by anbuharry** [KaiyangZhou/pytorch-vsumm-reinforce#79]
Hello, 

Can anyone send me a link to the office, lobby-based videos?

**Comment by SinDongHwan** [comment]
What are the office and lobby dataset?
Do you want to get videos at office or lobby?

**Comment by anbuharry** [comment]
> What are the office and lobby datasets?
> Do you want to get videos at the office or lobby?

yeah, I need office and lobby videos... I want to ask you one more doubt is there any possible way to reduce redundant frames while generating H5 dataset?

**Comment by SinDongHwan** [comment]
1. office and lobby videos.
  - search on YouTube.
2. way to reduce redundant frames while generating H5 dataset?
  - i think you make policies. (i.e, how to decide change points, which domain use, etc)

**Comment by anbuharry** [comment]
> 1. office and lobby videos.
>    
>    * search on YouTube.
> 2. way to reduce redundant frames while generating the H5 dataset?
>    
>    * I think you make policies. (i.e, how to decide change points, how to summarize using which methods, etc)

Hai @SinDongHwan

1.yeah .. when i am trying to generate a dataset for multi videos time taken is too high. that's why i am asking  another way to generate a dataset with important frames only 

2. i.e if i trying to generate a summarization for surveillence camera videos, how can i generate a video summary based on video captured timing is it poosible

**Comment by SinDongHwan** [comment]
Hi, @anbuharry 

If you want to summarize videos about surveillance videos, i think you can summarize videos using some methods like action recognition, recognition situation, etc.

**Comment by anbuharry** [comment]
> Hi, @anbuharry
> 
> If you want to summarize videos about surveillance videos, I think you can summarize videos using some methods like action recognition, recognition situation, etc.

Hi @SinDongHwan, sorry for making trouble

Can u give me a suggestion for a multi-video... if I give 2 videos as input how can I get 2 summary videos as output?

**Comment by SinDongHwan** [comment]
Hi, @anbuharry
Do you want to set as 1 at 2nd frame?
your code picks 1st, 15th, 30th frames.

**Comment by anbuharry** [comment]
> Hi, @anbuharry
> Do you want to set it as 1 at 2nd frame?
> your code picks 1st, 15th, 30th frames.

Hi @SinDongHwan 

That issue resolved...I slightly change the code and I reduced time instead of reading all frames.
```
success, frame = video_capture.read()
                if frame_idx % 15 == 0:

                    if success:

                        frame_feat = self._extract_feature(frame)                    
                        picks.append(frame_idx)

                        if video_feat_for_train is None:
                            video_feat_for_train = frame_feat
```

**Comment by anbuharry** [comment]
> Hi, @anbuharry
> Do you want to set as 1 at 2nd frame?
> your code picks 1st, 15th, 30th frames.

Hi @SinDongHwan 
 
Yes... I want to create a dataset with reading 15th frame not all the frame

**Comment by SinDongHwan** [comment]
Hi @anbuharry 
I think your codes are correct.

**Comment by anbuharry** [comment]
> Hi @anbuharry
> I think your codes are correct.

Hi @SinDongHwan 

But the only problem is in change points it shown below

![cps](https://user-images.githubusercontent.com/54160097/122162549-654c2180-ce91-11eb-838e-bcc9cd899380.png)

**Comment by SinDongHwan** [comment]
Hi, @anbuharry 
Did you input 15th frames into function for change points?

**Comment by anbuharry** [comment]
> Hi, @anbuharry
> Did you input 15th frames into a function for change points?

No, I don't know how to give input 15th frames into function for change points

**Comment by SinDongHwan** [comment]
I recommend that you analyze codes.

**Comment by anbuharry** [comment]
> I recommend that you analyze codes.
Hi @SinDongHwan 

I think I all done with video summarization but I had one and last doubt while generating a dataset is there any possible ways to reduce read all frames instead of reading 15,30,45th frames only

**Comment by Chuttyboy** [comment]
> I recommend that you analyze codes.

Hai @SinDongHwan 

Input 15th frames into function for change points issue resolved, Now my doubt is How can do the parallel process for 2 videos , and How can I read 2nd video from H5 dataset.

**Comment by SinDongHwan** [comment]
Hi, @Chuttyboy.
You can do the parallel process using multi processing/threading.
But I think summarizing two videos into one video is a different problem.

**Comment by Chuttyboy** [comment]
> Hi, @Chuttyboy.
> You can do the parallel process using multi processing/threading.
> But I think summarizing two videos into one video is a different problem.

Hai  @SinDongHwan 

Meanwhile generating a dataset video order changed  , For ex : vid_1 , vid_2 ,video_2 processing first , Is there any way to fix issue?

**Comment by SinDongHwan** [comment]
Hi, @Chuttyboy.

whenever generate datasets, create process/thread about each video.
each process/thread : feature -> change points -> save h5 
 or 
each process/thread : feature -> change points. if all videos finished, save h5.

if you want to improve speed, try to use batch when extract features.

Is this answer what you want?

**Comment by Chuttyboy** [comment]
> Hi, @Chuttyboy.
> 
> whenever generate datasets, create process/thread about each video.
> 
> > each process/thread : feature -> change points -> save h5
> 
> or
> 
> > each process/thread : feature -> change points. if all videos finished, save h5.
> 
> if you want to improve speed, try to use batch when extract features.
> 
> Is this answer what you want?

Thank you @SinDongHwan  
   Yeah ,This is exactly  I am asking

**Comment by Chuttyboy** [comment]
Hai, @SinDongHwan 
       How to do parallel processing for two video's ,i tried two ways 
1. Stored 2 video's in a H5 file ad processing it 
problem : 
How to give location for video 2 processing

2. Create Dataset for every single video

problem :
How to give two dataset in single arugument

Thank you

**Comment by SinDongHwan** [comment]
Hi, @Chuttyboy.

if you have two videos, create 2 process/thread.
ex) 100 videos, create 100 process/thread.

**Comment by Chuttyboy** [comment]
Hai @SinDongHwan Sorry for Giving trouble 

I tried multiprocessing for n videos but results will be same for all n video's, how can i pass ready 2nd video from a H5 dataset

**Comment by SinDongHwan** [comment]
Hi, @Chuttyboy.
I have one question to you.
What do you want to do?
multiple videos summarization? or each video summarization?
if first answer , i think you approaches as multi video summarization methods.

**Comment by Chuttyboy** [comment]
Hai @SinDongHwan 

Thank you,Thank you much @SinDongHwan  I glad to say this  I have done my project with multi video summarization under your support , You are the reason to done this work very soon. keep in touch for more future works on video summarization 

Once again Thank You

**Comment by Chuttyboy** [comment]
Hai @SinDongHwan 

frm_name = str(idx) + '.jpg' # zfill to zfill(6), delete zfill
                frm_path = osp.join(frm_dir, frm_name)
                print(frm_path)
                frm = cv2.imread(frm_path)
                print(frm)
                print("***********")
                frm = cv2.resize(frm, (args.width, args.height))
                vid_writer.write(frm)

In this  step i dont want to write a summary video here,i stored it in a variable, Now my doubt is if a taking 2 surveillance video   , i likely to sort frames by time based it that possible? if yes can you share your thought

**Comment by SinDongHwan** [comment]
Hi, @Chuttyboy 
If you have time_stamps, i think you can sort frames by time.
And I want you to take some question after more thought.

**Comment by Chuttyboy** [comment]
Hai @SinDongHwan 

v1 and v2 is nothing video1 and video 

A = [(0.jpg, ['v1', 'v2']), (15.jpg, ['v1', 'v2']), (30.jpg, [ 'v2'])

I have this list , now i  give two frame dir 

V1 = "frame_dir location "
v2 = "frame_dir location "

Now how can i get  0.jpg in video1 frm dir and ,video2 frm dir to write a summary video

**Comment by SinDongHwan** [comment]
Hi, @Chuttyboy.

Search "how to get file list python" on Google.
I think your questions is not regard this issue title, so if you have questions for different issue i think you should make a new issue.
