### ISSUE TITLE
Link to download dataset in repo is dead.

### ISSUE THREAD

**Issue by githubbinh** [KaiyangZhou/pytorch-vsumm-reinforce#80]
$ wget http://www.eecs.qmul.ac.uk/~kz303/vsumm-reinforce/datasets.tar.gz

--2021-06-16 22:02:40--  http://www.eecs.qmul.ac.uk/~kz303/vsumm-reinforce/datasets.tar.gz
Resolving www.eecs.qmul.ac.uk (www.eecs.qmul.ac.uk)... 138.37.95.147
Connecting to www.eecs.qmul.ac.uk (www.eecs.qmul.ac.uk)|138.37.95.147|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-16 22:02:41 ERROR 404: Not Found.

**Comment by Chuttyboy** [comment]
> $ wget http://www.eecs.qmul.ac.uk/~kz303/vsumm-reinforce/datasets.tar.gz
> 
> --2021-06-16 22:02:40-- http://www.eecs.qmul.ac.uk/~kz303/vsumm-reinforce/datasets.tar.gz
> Resolving [www.eecs.qmul.ac.uk](http://www.eecs.qmul.ac.uk) ([www.eecs.qmul.ac.uk](http://www.eecs.qmul.ac.uk))... 138.37.95.147
> Connecting to [www.eecs.qmul.ac.uk](http://www.eecs.qmul.ac.uk) ([www.eecs.qmul.ac.uk)|138.37.95.147|:80](http://www.eecs.qmul.ac.uk)%7C138.37.95.147%7C:80)... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2021-06-16 22:02:41 ERROR 404: Not Found.

Hi @githubbinh 

Here is the link for dataset:
          `https://drive.google.com/file/d/1XFizLbkpMX0NoPAe1P1WtvVn9KLwbZ7C/view`

**Comment by githubbinh** [comment]
ya,
thank you sir!
